name: Release branch

on:
  push:
    branches: [ release ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Prepare git
      run: |
        git config --global user.name "bot"
        git config --global user.email "Nikolaos.Georgiou@gmail.com"
    - name: Prepare release
      run: mvn -B -DpushChanges=false release:prepare
    - name: Push changes
      run: git push --follow-tags
    - name: Perform release
      run: ./scripts/deploy.sh new
      env:
        GPG_KEY: ${{ secrets.GPG_KEY }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
