name: Release branch

on:
  push:
    branches: [ release* ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: test
      run: >-
        ./scripts/release.py
        --gpg-key ${{ secrets.GPG_KEY }}
        --gpg-passphrase ${{ secrets.GPG_PASSPHRASE }}
        --gpg-key-file scripts/keys.asc
        --git-user-name bot
        --git-user-email Nikolaos.Georgiou@gmail.com
        --version-from-github-actions
      env:
        GPG_KEY: ${{ secrets.GPG_KEY }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
