name: Release

on:
  push:
    branches: [ release* ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # otherwise, git-cliff doesn't work
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Install git-cliff
      run: >-
        mkdir -p /home/runner/.local/bin
        && curl -L -o /tmp/git-cliff.tar.gz https://github.com/orhun/git-cliff/releases/download/v0.5.0/git-cliff-0.5.0-x86_64-unknown-linux-gnu.tar.gz
        && tar -zxf /tmp/git-cliff.tar.gz -C /tmp
        && cp /tmp/git-cliff-0.5.0/git-cliff /home/runner/.local/bin/
    - name: Release
      run: >-
        ./scripts/release.py
        release
        --gpg-key ${{ secrets.GPG_KEY }}
        --gpg-passphrase ${{ secrets.GPG_PASSPHRASE }}
        --gpg-key-file scripts/keys.asc
        --git-user-name bot
        --git-user-email Nikolaos.Georgiou@gmail.com
        --version-from-github-actions
        --maven-username ${{ secrets.OSSRH_USERNAME }}
        --maven-password ${{ secrets.OSSRH_PASSWORD }}
